<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Guid>246b4b7a-2e91-4ec6-8478-215be18bc01d</Guid>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <FileVersion>4.0.0.0</FileVersion>
    <RootNamespace>Jellyfin.Plugin.AutoChapterSkip</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <CodeAnalysisRuleSet>../jellyfin.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.9" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.9" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.376" PrivateAssets="All" />
    <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer" Version="1.1.31" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration/configPage.html" />
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration/configPage.html">
      <LogicalName>Jellyfin.Plugin.AutoChapterSkip.Configuration.configPage.html</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
